// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9xlsRz5KH87HNTJjCkxRavYmioxGf-vI',
    appId: '1:542687361114:web:736e6409584ba1ab0d4063',
    messagingSenderId: '542687361114',
    projectId: 'turisdu-fcc5a',
    authDomain: 'turisdu-fcc5a.firebaseapp.com',
    storageBucket: 'turisdu-fcc5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_587L9-F53C010W7zD74zQ3dn-wJYPQw',
    appId: '1:542687361114:android:90aa3f80f3e507df0d4063',
    messagingSenderId: '542687361114',
    projectId: 'turisdu-fcc5a',
    storageBucket: 'turisdu-fcc5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3rCg9IwDsavndCVwAbU6o4YxNwlPgqs',
    appId: '1:542687361114:ios:e30b7ba5c6e9645d0d4063',
    messagingSenderId: '542687361114',
    projectId: 'turisdu-fcc5a',
    storageBucket: 'turisdu-fcc5a.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM3rCg9IwDsavndCVwAbU6o4YxNwlPgqs',
    appId: '1:542687361114:ios:6848f308e460d8850d4063',
    messagingSenderId: '542687361114',
    projectId: 'turisdu-fcc5a',
    storageBucket: 'turisdu-fcc5a.appspot.com',
    iosBundleId: 'com.example.proyecto.RunnerTests',
  );
}
